### ISSUE TITLE
One month Pex groups (VIP-like)

### ISSUE THREAD

**Issue by Yaukz** [WooMinecraft/WooMinecraft#100]
Hey,

There's a way to give and after X days remove the player from that group?

Thanks! :)

**Comment by JayWood** [comment]
At this time no, but it is a planned feature.

**Comment by Yaukz** [comment]
There's something to do with Woo Memberships, maybe?

**Comment by JayWood** [comment]
I've thought of using WooSubscriptions, but have yet to get my hands on a copy.  It definitely is a planned feature, but no telling how I truely want to handle it yet.

Rather than requiring the user to spend $100+ on another plugin, I would honestly rather code in a 'date range' for a product with start/end commands.  ie. a set of commands to be ran on purchase, and a set of commands to be ran when the deal expired, etc...

**Comment by spannerman79** [comment]
> Rather than requiring the user to spend $100+ on another plugin

Its actually $199.00 - near $200USD/year.  For a server (like mine) that only financial worry is to only cover costs this is an extra cost that would be unfair to pass onto my "VIP" group for them to cover.

**Comment by spannerman79** [comment]
A little update for those that may want to know (and for you @JayWood )
I've switch my servers and bungee perm system to Luckperms.
Luckperms allows per server and per world permissions as well as timed permissions

One thing I have not tested yet was to have WooMinecraft sitting on the hub server - yet.

https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-permission-settemp

What Luckperms will do (if setup correctly) is that it will use the bungee message channel to push the perms network wide (if its a network wide permission being set, or push the perm to server/s defined) - thus needing a woocommerce specific addon no longer a requirement.
Even if its not a bungee network if you are using MySQL (which you would be anyway because of wordpress) Luckperms can push a sync based on perm changes. All comes down to what sort of setup you have and how you can use Luckperms to your advantage.

Not to mention Luckperms works on spigot 1.7.10 - 1.12, Cauldron 1.7.10 and even sponge servers.
