### ISSUE TITLE
1.10 support?

### ISSUE THREAD

**Issue by Devillion** [WooMinecraft/WooMinecraft#102]
I was super excited when I saw this plugin and then I read it's for 1.8.

You guy's going to get this updated for 1.10?

**Comment by TekkitCommando** [comment]
It should work for 1.10 :)

**Comment by JayWood** [comment]
@Devillion :scream: where does it say it's not for 1.10?

Check latest releases [here](https://github.com/WooMinecraft/WooMinecraft/releases) for the zip.

The latest release has a zip download which includes jar files from 1.7.10 all the way to 1.10.2 I think.

**Comment by Devillion** [comment]
Sorry, didn't realize the zip package had 1.10 version in it.

On this page: https://github.com/WooMinecraft/WooMinecraft

It only gives info about this: http://i.imgur.com/riSOR7F.png

Made think it wasn't available for other versions.

**Comment by JayWood** [comment]
@Devillion OH geeze, I need to fix that then.

As for the chargeback/refunds, yes I hope to do that, but I need to test w/ paypal ( specifically ) to see how WooCommerce handles those. So yea, it's on my radar, just hasn't been a top priority because people typically just insta-ban players who charge back ( historically ).

**Comment by Devillion** [comment]
When running a small server it's easy to know who's paypal belongs to which players to be able to ban them, but with 100's of players that's not so easy.

**Comment by JayWood** [comment]
Opened the above ticket, closing this one.
