### ISSUE TITLE
Order processing

### ISSUE THREAD

**Issue by Jogib** [WooMinecraft/WooMinecraft#110]
Since i'm an idiot on how to use Github properly, and actually wanted to pull a request for a new feature, I'm putting it here....

Is it possible to add a feature, where you can trace an order to see if the user actually got what he/she paid for?
Maybe by adding a process log or something to the java plugin?
Something like:
Order placed from "user" on website.
Order delivered to "user".

and if the user is not online:
Order placed from "user" on website.
Order awaiting delivery, "user" is not online.
........
........
........
"User" came online, going to deliver order.
Order delivered to "user"

**Comment by JayWood** [comment]
@Jogib yea this could be done in the log, really easily. ( Java side )

Ideally, I'm sure you want a log of orders by username? I could probably do this on the wordpress side and add a 'username' column to WooCommerce orders so you could filter by that and see if it was delivered or not.

**Comment by TekkitCommando** [comment]
@JayWood I know I am not on the team anymore but maybe it is worth considering an API for WooMinecraft so that users can do these non-priority features themselves.

**Comment by Jogib** [comment]
@JayWood
I'm NOT sure if the ordering should be by username or something else. 

Maybe something really simple could be done. I'll try to explain. 
The product has to be marked as virtual and downloadable in woocommerce, as it is right now. 
What if you could remove the downloadable mark, and let the plugin tell woocommerce when the product has been delivered and then change the order as complete?

You follow me?

**Comment by JayWood** [comment]
@Jogib Your overall goal is to determine if an order has been delivered or not, ie. commands sent, correct?

I rely on WooCommerce to determine when an order is complete, I wouldn't want to be responsible for someone getting the 'product' ( commands ) without WooCommerce determining when the order is complete.

The pseudo handshake works like so.

WordPress Side ( Step 1 )
* User creates order
* Commands are stored as a 'pending' command for that order, with the user's order name as well.

Java Side ( Step 1 )
* MC contacts your web server and says "he give me all pending commands"
* MC Then checks if users are online ( despite a recent bug )
* If a user is online, MC runs the pending commands in that order.
* MC Then stores that order ( and all other ) order ID's in a data set

Java Side ( Step 2 )
* Once all commands have been ran a request is sent to your web server
* This request contains a list of all order ID's of which all commands have been ran

WordPress Side ( Step 2 )
* WordPress is always listening for an incoming request based on your server key for processed orders.
* Upon receiving your server key, and the list of process orders WP walks over each order, and sets the commands as delivered.

-----------------------------------------

With that being said ( I know it's an interesting process ), a simple solution here will be to look for a 'delivered' key on the WordPress side to know when commands for a particular order are delivered.

So, to your point of:
> I'm not sure if the ordering should be by username or something else.

It has to be, and always will be, tied to a username ( Minecraft Username ) if not, we cannot associate a 'logged out' user with a Minecraft user. Which is why users must enter their name on the checkout form.

Again, the simplest solution here will be for me to create a column or some sort of identifier on the Orders list in the admin for owners to see "yea this was delivered".

**Comment by JayWood** [comment]
@TekkitCommando to your point of making an API available, it already is :smile: just gotta know how to hook into it.

**Comment by Jogib** [comment]
I can't quite get it to work, like you explained.
I will get back to this as soon as i have some more time to test.

**Comment by Jogib** [comment]
@JayWood 
The thing is, according to your step by step, that something doesn't quite add up.

**Wordpress side (step 1)**
Second step here already cracks the film.
For the product to process automatically, it must be ticked as a downloadable product, which mean by woocommerce that the order will change state "Completed", right after payment. As long as the order stays in the "Pending" state, nothing happens on either WP or MC server.

**Java Side ( Step 1 )**
Step 2 here is working more or less.
If we imagine that step 2 in WP side step 1 is working as it should, the MC server console shows the following output: [20:44:36 INFO]: [WooMinecraft] []
Here it might be a good idea, that the actually told which orders are awaiting a user to come online?
When we get to step 3 you get the following output in the console: 
[20:45:06 INFO]: [WooMinecraft] [16]
[20:45:07 INFO]: Given [Golden Apple] * 64 to Jogib
This is great! MC actually tells what order has been processed and delivered to the user.

**Java Side ( Step 2 ) & WordPress Side ( Step 2 )**
I can't say for sure if things are working as it should from here on since step 2 in WP side step 1 is not working as it should?

Hope you understand what i mean - English is not my main language. (Danish is)

**Comment by JayWood** [comment]
@Jogib based on your response on #109 this should be resolved, if not a duplicate at this point?  Overall I just wanted to give you an idea of what the 'intent' was, not rather it was working or broken :smile:

**Comment by eric2788** [comment]
although it has no error now,it still has also executed my hisotry(Old) product command.....

**Comment by eric2788** [comment]
@JayWood can you make the command can be executed when that player is offline ?
and also can this plugin can set whnether only support premium players.
Error while connecting to MojangAPI just a warning,it still can executed the command for non-premium players
btw that's plugin's good,the bug has fixed totally

**Comment by JayWood** [comment]
I can make commands be executed for offline players, yes, but what scenario would you require running a command with a user offline? Ranks? Currently users are required to be online for a command to run.

> Error while connecting to MojangAPI
I will not go around this, you're at Mojang's mercy. I use Mojang to validate the user's account, sorry.

Glad to hear the plugin is working as expected :+1:

**Comment by Jogib** [comment]
> @Jogib based on your response on #109 this should be resolved, if not a duplicate at this point? Overall I just wanted to give you an idea of what the 'intent' was, not rather it was working or broken 😄

@JayWood Now you got my 2 cents :wink:

**Comment by JayWood** [comment]
@Jogib What portion of this is still an ongoing issue? Sorry, tracking multiple threads gets me confused at times, a little clarity would be awesome.

**Comment by eric2788** [comment]
yes i want to execute offline command like give rank, donate point etc

when i write the  non premium player username in field,it will display error while connecting to mojangAPI
but they can still bought the item
so it that message just for debug?
i am looking for the wp-plugin can add a option like disable non-premium(cracked minecraft players) players to buy the item,etc

**Comment by JayWood** [comment]
Are you saying that the non-premium players are able to complete a checkout for your items??? This is not supposed to happen, the error shown is designed to disable users from completing a purchase if the minecraft account isn't valid.

Can you give me the MC username you were using to test? This plugin is not supposed to support non-paid accounts, nor will it ever do so. IF this is happening it's a bug.

**Comment by eric2788** [comment]
i have used LavaIve for cracked players

**Comment by JayWood** [comment]
This plugin will **not** support cracked accounts.

**Comment by eric2788** [comment]
@JayWood  i know, and i want to disable cracked player donation too, but i have said this system still worked on cracked players

**Comment by JayWood** [comment]
This is a separate bug, opened a new ticket above, closing this for cleanliness
