### ISSUE TITLE
Infinitly recurring commands

### ISSUE THREAD

**Issue by timitimitimi** [WooMinecraft/WooMinecraft#122]
Hi, as mentionned on spigot forums, i'm using your latest releases of both wp and mc plugins. An item is purchased, marked as completed.. Mc plugin checks manually or not, and command is sent. And repeat, and again, over and over again! 😄 

I read somewhere there is some Meta-data added to the order, how can i check if this done ?

**Comment by timitimitimi** [comment]
wanted to add, server runs kCauldron, MC 1.7.10

**Comment by JayWood** [comment]
@timitimitimi who is your host, and what is the url?

**Comment by timitimitimi** [comment]
I'm hosting the game+web server on a dedi @ OVH. url is the IP/directory. If we can pm, i'll share more info. It's running latest Apache2/PHP7 with many needed extensions. Latest Java 8 x64 for MC server.
It's still functional, it gives the message all has been processed, and proceeds, message it didn't give with previous url. What more.. Latest WP and Woo. Thx again.

**Comment by JayWood** [comment]
Well I know the host has nothing to do with it, I myself host on a dedi from SYS ( subsidiary of OVH ). I use NginX though, and my server configs are super customized ( I moved from apache some time ago ).

I ask about the host because some of these 'FREE' hosts do a redirect when loading the main page for the first time as a way of handling bots which causes the issue.

You can add me on skype if you'd like - 'jjswebs' -- just be sure to put in some sort of message regarding this because I do get some weird contact requests at times.

You can also reach me also via my contact form on my site - http://plugish.com/contact-me/

It IS still possible the issue is with the apache config. Like why would you have to use `/index.php` in the url field, that's just weird for WordPress.

**Comment by JayWood** [comment]
@timitimitimi so this was a server config issue?

**Comment by timitimitimi** [comment]
Yes, I guess the URL rewrite was an issue.

Le 7 janv. 2017 05:31, "JayWood" <notifications@github.com> a écrit :

@timitimitimi <https://github.com/timitimitimi> so this was a server config
issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WooMinecraft/WooMinecraft/issues/122#issuecomment-271062162>,
or mute the thread
