### ISSUE TITLE
Help with multiple servers

### ISSUE THREAD

**Issue by Valcoxic** [WooMinecraft/WooMinecraft#133]
I have multiple servers connected with bungeecord.
For some time it was not possible when they bought one rank that they would get it across all servers.
Then I found that you made a "beta" plugin for wordpress which support multiple servers so I installed it. So far so good but when they purchase it it will only work on the first servers that does the woo check. That server will get the rank and all but any other server will say that there're no purchases.

Could you give me advise please?
PS: Sorry if the english is a bit cracky

**Comment by madmaty** [comment]
The simplest way would be to run a number of commands with each purchase 

/give item %s world
/give item %s world2

Change the commands obviously I have no clue what group / permission manager your using
they should all execute at the same time

**Comment by JayWood** [comment]
@Valcoxic Multi-server support is not built to 'run a command on all servers' rather; it was built from more of a 'separate commands for each server' aspect.

At this point I'm not even sure how that would be accomplished, you'd have to simultaneously run a command on every server. Perhaps this is due to my ignorance of Bungee Cord, but I'm sure that would go hand-in-hand with #132 as the user cannot be logged in on all servers at the same time.

**Comment by Valcoxic** [comment]
Thank you for your responses. I will try to figure out if I can make it work. Thanks anyway ;)
