### ISSUE TITLE
Issue, string 1 column 1 §???

### ISSUE THREAD

**Issue by ProxTricky** [WooMinecraft/WooMinecraft#216]
https://pastebin.com/huQpavTd

ikoula, debian 9
play.satyria.fr
https://www.satyria.fr

Hi, my problem is, i don't even know... If u see what is the problem with the pastebin, i would be greatfull!
Sorry for my poor english, french guy here!

**Comment by JayWood** [comment]
The error ` Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

The issue is typically with a redirect but looking at your site doesn't seem to have a redirect. However looking at the JSON feed it seems to be lacking the `/wmc` endpoint. Make sure you install the WordPress plugin version ( latest ) and activate it.

**Comment by ProxTricky** [comment]
i'm not pretty sure about what i've did but, i just put my site url even if it's an https in the url section in the minecraft plugins config ? and create a key and paste it in it ? is that's all ?

**Comment by ProxTricky** [comment]
Okay, my bad, just forgot to put the httpS ... Thank's a lot!
