### ISSUE TITLE
key provided in request is invalid

### ISSUE THREAD

**Issue by Avomance** [WooMinecraft/WooMinecraft#277]
I am really sorry if I have provided this help request in the wrong format, but I am not a coder, just a Minecraft YTuber, and am receiving this error message on use of "/woo check" command in game on the server I have connected WooMinecraft to:

key provided in request is invalid

my wordpress and .config keys match as per the configuration instructions:

- lang: "en"

- update_interval: 60 (Have I set this too low for the programme to cope with?)

- url: "https://avoverse.com"

- prettyPermalinks: true

- restBasePath: ""

- key: "I HAVE MY KEY INSERTED HERE THAT MATCHES WP"

- debug: true

If anyone can help me or direct me to how to solve this problem I would be hugely grateful.

I am running in paper 1.18.1 on Apex Hosting

Thanks in advance loads

**Comment by Avomance** [comment]
Update - It now states that all items are processed on using /woo check... but no items are delivered? I have obviously not ticked a box or something - any clues hugely appreciated

am using the command give %s 264 64 to get 64 diamonds as a test

**Comment by JayWood** [comment]
Orders must be set to completed.

**Comment by Avomance** [comment]
Thank you Jay for coming back so fast - orders are set to completed... and they are being received in the game now.
They are, however, being delivered repeatedly over and over on a loop every cycle, or whenever I use /woo check, even though the message in game states "all purchases processed".
I cannot find a way to stop them in my test world, and any NEW orders aren't coming in after them.

I am certain there is a really simple explanation for this, but cancelling the order does NOT stop the deliveries every 60 seconds (which is what I set my reset time to in my config)

I feel I am VERY close to getting it done, but this little problem is stopping progress.

**Comment by JayWood** [comment]
This is sometimes due to anti-botting measures preventing the `POST` of data to the REST endpoint.  The reason is really because the request sends a basic header which some site's consider as a bot and your web server is either redirecting the request or serving up some other sort of anti-bot measure. Unfortunately this is something you'll need to work with your HOST on or you'll need to enable `POST` data to the REST endpoint ( if you're using any sort of API authorization plugins ).

The endpoint( unless you changed the config ) is one of the two:

* `/wp-json/wmc/v1/server/<key>` - default
* `/index.php?rest_route=/wmc/v1/server/` - if pretty permalinks is disabled

When the initial "get all orders" request is made, it's made as a `GET` which is what websites use in general. To update the data a `POST` is sent with a body of JSON data to the same endpoint. You can see all that in action here - https://github.com/WooMinecraft/WooMinecraft/blob/c037305e0a0ba8c03424823001fc3ef397f84805/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L242

**Comment by Avomance** [comment]
Thanks Jay… I will have a look at that and see if I can work through it

Thank you for the crazy fast response

**Comment by JayWood** [comment]
Closing as no reply in a month or so.
