### ISSUE TITLE
When to Grab UUIDs

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#51]

**Comment by JayWood** [comment]
This task is to open discussion surrounding the question above, exactly when would be the best time to get the UUIDs?

My first initial thought was to do this in PHP on the checkout form, the entire process would look like so:

* When the player enters their name, an extra field is populated which also puts in their current UUID.
* The Playername, and UUID would then be saved to the database
* In theory we could log just the UUID, but more on that shortly.
* The idea is that it's going to be REALLY rare for a user to change their username between the time they purchase an item/package, and when it's redeemed.  If that does happen, more than likely the administrator will find out and handle it accordingly right?

From what I understand, the UUID will ALWAYS be assigned to the same player, though they can change their name, the UUID will never change. ( If I understand this API correctly ), so, wouldn't it be logical to base purchases off of solely UUID's instead of player names?

If that's the case, the UUID is what needs to be saved, not just the player name, the name is irrelevant in this situation.  The name is essentially a gateway in obtaining the user's actual UUID.  So we would need to store the UUID and send IT, not the name, to the minecraft server right? @TekkitCommando

**Comment by TekkitCommando** [comment]
@JayWood Correct on the api, technically we could store the uuid ONLY and just have a uuid to player name function or separate class which would translate that uuid to the latest username from mojangs database and send the commands accordingly with the latest username. I guess if you want to stay along the lines of whats recommended and less deprecated just translating the uuid to a latest username from mojangs database is a way to get rid of player.getName entirely or almost entirely. Since we always need a username for the command part because a lot of plugins are using player names still and not uuids. So instead of a UUID to Username class/function we use only uuid's and have a function get the players name from that uuid ONLY when sending the commands (Which may make it better to do it on the PHP side of things). Also another thing we could do if you want to store both the UUID and Username is make a PlayerLoginEvent that checks their uuid and checks the database of uuids and resends their commands if the username is changed because servers don't save that stuff usually. Might still be good to have a config option to disable the changedName checker which could bring the java side in. Doing something like that would put us on top of the other donation systems since they don't have a way to protect the players who change their name. @JayWood What do you think?

**Comment by JayWood** [comment]
@TekkitCommando Since the `getPlayer( UUID uuid )` function  returns an instance of `Player` and we know that UUID is always unique to the player, we really don't even need a UUID to player name function I wouldn't think.

We're not really storing anything in the server for users to read. Furthermore, if the user is currently signed onto the server we could just get his player name by `Player.getDisplayName()` or `Player.getPlayerListName()` once we get the Player instance by the UUID couldn't we, no need to involve mojang?

I guess what I'm getting at is, we technically ( now that I think about it ) only need to involve the Mojang API once, which is at the time of purchase/checkout.  At this point we get and store the user's UUID.

Then, when `WooMinecraft.check()` is ran, we send the UUID **instead of** the player name.  Since we know the UUID is unique to the player, regardless of what server he's on.

Therefore the only real time we need the player name is when he/she enters it in the box during checkout, we literally don't even save it, and only use it to contact the Mojang API on the WordPress side to acquire the current UUID.

Does this sound about right?

**Comment by TekkitCommando** [comment]
@JayWood Oh yes, forgot about that, sorry xD, My meaning on the UUID lookup for the player on server login was for name changes, since they bought the product whatever that may be they may have changed there name, they don't have their stuff anymore so storing both their player name and uuid is good so the code can tell if the player with that uuid has a different name then the one stored on the database and it runs the commands again. So Good idea or nah? I thought it would help with name changes and server owners having to do less work :)

**Comment by JayWood** [comment]
If they don't have their stuff, and we're using only the UUID, then that never changes, we could just re-issue the commands based on UUID no? The player name would be nothing more than a tidbit of information to the server owner saying "A is now B" - not really for the purpose of re-delivering commands?

**Comment by TekkitCommando** [comment]
But the UUID doesn't change so don't you need to store a username to see if the changed the name since they bought the stuff

**Comment by JayWood** [comment]
That's what I'm saying, so what's the purpose of talking to Mojang at any other point than purchase ( to get the UUID )

**Comment by TekkitCommando** [comment]
I meant talking to the store database not mojangs database sorry :P

**Comment by JayWood** [comment]
AHHHH Now I understand. The problem we're going to run into, and I know cuz I've hit it before, is hitting the web server's post_max_size limit.  Which limits the amount of data we can send to a server. This isn't ONLY with UUIDs, it's also possible to happen with usernames ( a server with 200 users ( active ) may not process on a default server setup ).

What do you think about this, instead of the handshake we have going on right now which is:
Minecraft -> Web Server -> [ processes request ] -> Minecraft -> [ processes donations ]

What would you think about this: Instead of grabbing servers on the minecraft server, processing it, putting it into a comma-delimited list, then posting it to the server, why don't we do this?

Let's make the JSON feed available 24/7 we'd cut the code by about 2/3rds. So what we could do then is literally just send the web server our key and grab ALL the orders.  Regardless of online players, since both you and I know, java is pretty efficient at processing that data.

Of course to protect the feed, we'd just require the key in the URL like we're already doing. This completely circumvents hitting the post_max_size since we won't be posting anything at all we're literally just opening a stream ( like we already do ) and walk over it one by one checking if that player is online.

**Comment by TekkitCommando** [comment]
Ah ok, sounds doable and it could work awesomely :) I like it.

**Comment by HappyHarm** [comment]
Does php also grabs non premium players their uuids?

**Comment by TekkitCommando** [comment]
I am not even sure non premium players have uuids cuz non premium players don't have Mojang accounts I think but maybe they do and if so maybe they have UUID's I have never heard of it though

**Comment by JayWood** [comment]
@HappyHarm by non-premium are you talking 'unpaid' accounts? If that's the case, I'd prefer NOT to support offline-mode servers.

**Comment by HappyHarm** [comment]
@JayWood Yeah ment that with it. I'm not sure but I thought that offline mode servers have ''their own'' UUID system that's stored in the server files. So I think that for offline mode servers the UUID fetcher should be on the server side (I could be wrong). 

But maybe there could be an option for offline/online mode servers or the UUID has to be grabbed?

**Comment by JayWood** [comment]
Closing, merging with #36
