### ISSUE TITLE
Not running commands

### ISSUE THREAD

**Issue by FinlayDaG33k** [WooMinecraft/WooMinecraft#76]
when I do a test purchase, the commands that I run (`say %s just did  a test purchase`) are not ran.  
going to `https://www.finlaydag33k.nl/?woo_minecraft=check&key=SUPERSECRETKEY` in my browser says: `{"success":false,"data":{"msg":"Method or Names parameter was not set.","code":7}}`

I also noticed that I cannot enter my Minecraft username when doing the purchase...

**Comment by TekkitCommando** [comment]
Hmm that's been a problem but only for a couple people. @JayWood will probably have to look into this since it is a Wordpress side thing, I know there was other problems only a couple people were having but worked for me which is weird. I will do a fresh install of my Wordpress site and setup a fresh server and see if I can reproduce this problem :) Thank you for the bug report.

**Comment by FinlayDaG33k** [comment]
also might be helpful to know:the console doesn't seem to show any error.

**Comment by TekkitCommando** [comment]
It won't unless it's a Java error

**Comment by HappyHarm** [comment]
Are you using the latest woocommerce and WooMinecraft wordpress plugin version? Also do you have any other woocommerce/wordpress plugins that could conflict into this one by editing the required fields for example?

**Comment by FinlayDaG33k** [comment]
Im running WooMinecraft `Version 1.0.1` woocommerce `Version 2.5.2` but I do have a plugin that changes the required fields called `WooCommerce Remove Billing Fields for Free Virtual Products`

**Comment by JayWood** [comment]
@FinlayDaG33k Oh dear, we're hooked into the billing fields area, so if that's removed in some fashion, then that would indeed break it.  BUT, since that plugin was disabled, it wouldn't explain why it broke unless that plugin, for some reason, copied over a template to your theme.

On a second note, no, you will not get anything when simply 'accessing the url', you must send `$_POST` data as well with a key of `names` in order to get a response, but, since your checkout field is missing the 'name' area for the MC username, simply purchasing the product isn't enough.

I'm hoping to get some time to look into this issue before sunday, i'll report back here.

**Comment by JayWood** [comment]
@TekkitCommando On a side note, I'm going to look and see if there's a more logical location to put the username field, since people are having so many issues with it's current location during checkout.

**Comment by TekkitCommando** [comment]
@JayWood Ok

**Comment by FinlayDaG33k** [comment]
I compared the HTML output of the checkout page with and without the `WooCommerce Remove Billing Fields for Free Virtual Products` and the only thing major that was changed (except for some Cloudflare stuff) is on these pastebin links:
[Without](http://pastebin.com/e5BrZAYS)
[With](http://pastebin.com/2VMSAzCr)

hope this might helpout a little

**Comment by HappyHarm** [comment]
Don't know really but you could try to reinstall the WooMinecraft plugin when that billing thing is disabled. Maybe that will readd the fields.

**Comment by FinlayDaG33k** [comment]
I've reinstalled it with the billing thing disabled, but no luck.

**Comment by daytonmills** [comment]
The checkout field is missing the 'name' area for the MC username. Although I haven't used any plugins to remove the billing fields. This plugin is exactly what I was looking for, so I hope it's fixed soon.

**Comment by JayWood** [comment]
I plan to work on this tomorrow to see what is going on, but if @FinlayDaG33k and @daytonmills can at minimum check with the default theme ( 2015 or 2016 ) and let me know if that works.

If indeed that does work , that would mean the issue would be with the theme.  Since with wooCommerce, you can override checkout templates by copying them over to your theme.

Alternatively, if deactivating your theme is not an option, you can look in your theme for a file under this specific directory `woocommerce/checkout/form-checkout.php` If that folder, and specifically that file exist, chances are that file is omitting the action hook the plugin needs to activate.

This request is a shot in the dark of course, but definitely worth looking into.

**Comment by FinlayDaG33k** [comment]
I tried it with the `2015` theme, but unfortunately, no luck... 
I'm using the `Sparkling theme` for the actual site.

**Comment by daytonmills** [comment]
It didn't work for me on the 2015 theme either. I am using the [Klein](http://themeforest.net/item/klein-a-nittygritty-community-theme/5418518) theme.

**Comment by JayWood** [comment]
On the off chance you trust me to access your site, I'd like to get into the back-end and see how the product is setup.  If @FinlayDaG33k or @daytonmills can shoot me a user/password for the site at my skype `jjswebs` that'd be great.

The only place I can see this failing is in the has_items check.  The way it works is it checks your cart for items which have commands listed, if no item has commands, then you won't get the field.  I've installed both themes, and i have it working just fine :cry:

**Comment by JayWood** [comment]
@FinlayDaG33k @daytonmills Ignore that request, I've reproduced the error **facepalm** expect a fix shortly....

**Comment by JayWood** [comment]
@FinlayDaG33k - you should get an update request in your WP dashboard shortly for the plugin.  WHen you're satisfied it's working as intended, please close this ticket :+1:

**Comment by FinlayDaG33k** [comment]
@JayWood I'll be waiting for the update then. how long do you think it will take?

**Comment by JayWood** [comment]
@FinlayDaG33k should be about 30 minutes, but you can also download the zip directly here; https://github.com/WooMinecraft/woominecraft-wp/archive/master.zip

**Comment by FinlayDaG33k** [comment]
it seems to work! yay :D 

also, the version is still on 1.0.2 (should be 1.0.3 I guess but it's no big deal)

**Comment by JayWood** [comment]
haha yea I tried fixing it with new commits, but the versioning will have to wait until next update apparently. It working is the main goal :)
