### ISSUE TITLE
an internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by NimaGame** [WooMinecraft/WooMinecraft#85]
Hi,
This is a nice plugin!
And I really love it!
But I can't use it on my server.
Please update it to 1.9 faster!
When I use /woo check it show me this error : internal error occurred while attempting to perform this command
Please help me!
thank you.

**Comment by TekkitCommando** [comment]
Woo check has nothing to do with bukkit really. Please a link to your config by pasting the config with pastebin/pastie.

**Comment by NimaGame** [comment]
http://pastebin.com/2i6gd3ba

**Comment by TekkitCommando** [comment]
Have you added the key to wordpress panel?

**Comment by JayWood** [comment]
WMC is currently not built against 1.9 - so if you're trying to run it in 1.9, there is no 'bug' aside from the fact it's not built to run in 1.9

If, however, this bug emerged from 1.8, then yea this is a bug.

**Comment by JayWood** [comment]
@NimaGame 

Untested 1.9.4 build, have at it, report bugs, etc... just make sure to include any logs.

[WooMinecraft-Bukkit-1.9.4R0.1-1.0.4-SNAPSHOT.zip](https://github.com/WooMinecraft/WooMinecraft/files/305952/WooMinecraft-Bukkit-1.9.4R0.1-1.0.4-SNAPSHOT.zip)

**Comment by NimaGame** [comment]
Works fine!
Thank you :+1:

**Comment by TekkitCommando** [comment]
@JayWood I will update the Bukkit/Spigot repos with that jar and just tag it with snapshot.

**Comment by NimaGame** [comment]
[WooMinecraft] Cannot open Data Output Stream!
[WooMinecraft] Connection refused

**Comment by TekkitCommando** [comment]
Connection refused to your WordPress site, right? @JayWood

**Comment by NimaGame** [comment]
{"success":false,"data":{"msg":"Method or Names parameter was not set.","request_data":{"woo_minecraft":"check","key":"be83bb8262614e1fafbee570bd36f28c"},"code":7}} :-?

**Comment by TekkitCommando** [comment]
You don't have to hide your key, it doesn't give us access to your server. :P but @JayWood would know the cause of connection refused more then me.

**Comment by JayWood** [comment]
@NimaGame yea the key is purely so someone can access the list of stored commands, it's really simple to change it of course.  

I'm working on some tweaks that would essentially remove that anyhow.

@TekkitCommando this is the exact same issue as another ticket, second offense in fact. For some reason the names isn't posting to his server.

If we can get info on your WordPress server, like what OS it is, how are PHP scripts handled ( NginX or Apache ) what PHP version, etc... the more info you can give the more it will help us in determining the root cause of the names not getting posted to WordPress.

And to be clear, there was indeed player(s) online when this ran right?  Could you post the full log from that?

**Comment by NimaGame** [comment]
To be clear, we are using Debian Wheezy, PHP 5.4 and Nginx 1.2.1. There are online players in the server when we test this

**Comment by JayWood** [comment]
@NimaGame yep, confirmed bug. 

@TekkitCommando modifications will need to be made ( which I think we're already doing ) in the Java side of things to not 'post' names to the server.  Instead, on the WordPress side we'll be simply outputting a feed, instead.

This willl fix this issue.  I'm wondering if that's something we can just put ahead of anything else we got going on, since I believe that would fix the bulk of these issues?

**Comment by TekkitCommando** [comment]
@JayWood Yeah I think this is a priority. However I know PHP now, still not sure how to make WordPress plugins though I should be able to learn pretty quickly.

Hear me out here. Isn't it possible to do what we have been doing but in a different way. Add all commands needing to be ran to its own database and then those commands can be sent when the order is confirmed ( which I hope he did check if the payment was confirmed) and use some Java database code to manage the commands needing to be sent to the server instead of screwing around with all the json. That would effectively end the bugs. Where Java will just retrieve the commands and do what needs to be done sending them to the players and PHP will manage the commands that need to be added to the database it needs. I think the plugin will be more lightweight that way. If you understand my meaning. May setup a branch and try it as a proof of concept and a way to better explain.

**Comment by JayWood** [comment]
The amount of read/write operations would be significantly higher if we were to go down that route, add to that the fact that the commands would be essentially stored in two locations ( wp database, and java memory/db ).

Kind of inefficient no?  A solution to this single bug would be to provide a json feed ( which we already do ) but remove the `$_POST` requirement.  Right now WMC is actually sending the web server a 'list' of names ( or its supposed to ) so it knows what commands to run.

However, on the WP side of things, I've already started on a modification to that here: https://github.com/WooMinecraft/woominecraft-wp/tree/feature/json-feed

Basically if a key is provided, the java would get a list of all commands to be ran, without having to 'send' names to request.

Again, this is already in the works just need to finish it up.  Gives me something to do this weekend?

The main problem is you cannot 'technically' separate the commands from WordPress since in WordPress they're already stored in the DB by the user inputting them. They're then stored against the username in the db upon purchase ( so we know who bought what ).  So even then, to get them from the WP db to java, you'll have to 'open'  the SQL connection, which in most cases like WPEngine and other hosts, they lock down MySQL to local connections only.  So attempting to connect to the database from an external source, will fail. Which means more support tickets.

**Comment by TekkitCommando** [comment]
Ah ok. Gotcha.

**Comment by JayWood** [comment]
@TekkitCommando was looking into this in the AM today.  I think I know why this is happening.  Looking into Java Thread Safety here - http://stackoverflow.com/questions/6324085/what-is-thread-safe-in-java
http://stackoverflow.com/questions/3272681/httpurlconnection-thread-safety

Since in the connection class the input and output streams are separated, it's possible they're both on different memory threads ( think of threads like lanes in a highway ).

I'm working on switching all these connections over to HTTPClient which will take some of the guess work out of posting/getting data.  See #88 

While HTTPClient is not synchronized, the code is much lighter, and making it synchronized will be MUCH easier.

**Comment by JayWood** [comment]
For reference, HTTP docs - https://hc.apache.org/httpcomponents-core-ga/examples.html

**Comment by TekkitCommando** [comment]
Ok. Is it better for me to wait and see what you push or do you have something you want me to work on that won't mess with your flow :P

**Comment by JayWood** [comment]
@TekkitCommando feel free to start on anything you want.  Just don't have much time lately, have that comissioned project to work on first.

It'll help get me up to speed down the road if you reference tickets you're working on in your commits, ie, adding things like ` - ref #88` for example.

**Comment by TekkitCommando** [comment]
Ok :)

**Comment by NimaGame** [comment]
@TekkitCommando  @JayWood 
Hello guys, how are you?
Did you fixed the problem?

**Comment by TekkitCommando** [comment]
@NimaGame Jay has a brain child that he is nurturing to solve the issues rn :P

**Comment by JayWood** [comment]
@NimaGame I've had some pre-existing engagements I had to settle before I began working on this. I'm convinced that the issue is the mult-threading in java. Life does tend to get in the way of side projects sometimes, my apologies.

I'll notify you as soon as I fix the issue.

**Comment by JayWood** [comment]
#88 is considered fixed, and therefore this will be once the release is out.
