### ISSUE TITLE
What you want me to do?

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#93]
I read and replied to your Spigot PM. What you want me to do friend? :) I will start work on it today.

**Comment by JayWood** [comment]
You had some pretty good ideas for #63 #84 would be pretty sweet to see how you do that.  I have little experience with GUI's and signs so... kind of out of my range.

**Comment by TekkitCommando** [comment]
Alright cool. I will get to work with that.

**Comment by TekkitCommando** [comment]
@JayWood I have done these GUI's and signs so many times this will be easy but we need to be saving the product name to a json file as well so that the signs and gui icons have something to pull data from.

**Comment by JayWood** [comment]
@TekkitCommando could we make it dynamic? Ie, do a HTTP Get request to the wordpress API for the product?

The reason I ask is that in WordPress now there's a built in JSON API and WooCommerce also has support for products ( if enabled in the admin ). You can see the different routes available here: http://agedcraft.net/wp-json/wc/v1

Currently the products endpoint requires an oauth setup, but temporarily I can expose without oauth.

Given that, also, we can now leverage the oauth key system from WC instead of our usual server key stuff. Something I'll look into on the WordPress side.

By using the API, we could build a caching system to update our local cache, and thereby updating them on a regular basis, should a product change on the website.

**Comment by TekkitCommando** [comment]
Alright yeah. As long as I can pull the product names and save them to a variable(s) and then be able to translate the product name to a link on ItemClick or onSignClick. I am not sure how to make a get request to the WordPress API for the product names though. Do you have any documentation stuff I can read?

**Comment by JayWood** [comment]
https://docs.woothemes.com/document/woocommerce-rest-api/

**Comment by TekkitCommando** [comment]
Will that have any api example?

**Comment by TekkitCommando** [comment]
@JayWood Check spigot I sent you sort of a "business inquiry" or "partnering offer" that I want you to read.

**Comment by TekkitCommando** [comment]
@JayWood Added the event handler and gui code. Kept the code to register the event commented out though so the plugin doesn't throw errors when compiled. We need to think of a way to make the amount of icons based on the amount of products but you can dynamically name variables in Java last I checked but there needs to be a way to do it.
